# Generated by Django 5.0.2 on 2024-03-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
