# Generated by Django 5.0.3 on 2024-06-01 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='addresses',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='couponusage',
        #     name='Coupon',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        # ),
        # migrations.AddField(
        #     model_name='couponusage',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='discount',
        #     name='coupon',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupon'),
        # ),
        # migrations.AddField(
        #     model_name='discount',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='brand',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brand'),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='category',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        # ),
        # migrations.AddField(
        #     model_name='sale',
        #     name='product',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        # ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='user',
        #     field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='variation',
        #     name='product',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        # ),
        # migrations.AddField(
        #     model_name='wishlist',
        #     name='product',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        # ),
        # migrations.AddField(
        #     model_name='wishlist',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
