# Generated by Django 5.0.2 on 2024-02-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
