# Generated by Django 5.0.2 on 2024-03-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_userprofile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
