# Generated by Django 5.0.2 on 2024-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_discount_percentage_offer_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offers',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
