# Generated by Django 5.0.2 on 2024-03-23 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_offer_remove_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='expires_on',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='offer',
            name='ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Offer Ends at'),
        ),
        migrations.AddField(
            model_name='offer',
            name='maximum_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maximum Amount'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_on',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category')], default='product', max_length=20, verbose_name='Offer On'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_product_category',
            field=models.CharField(default='', max_length=255, verbose_name='Offered Product/Category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Offer Starts at'),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Offer Name'),
        ),
    ]
