# Generated by Django 5.0.2 on 2024-03-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_offer_expires_on_remove_offer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='maximum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Amount'),
        ),
    ]
