# Generated by Django 5.0.2 on 2024-03-25 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_offer_maximum_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offered_product_category',
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.product', verbose_name='Product'),
        ),
    ]
