# Generated by Django 5.0.3 on 2024-03-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_offer_offered_product_category_offer_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerproductassociation',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offerproductassociation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offerproductassociation',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OfferProductAssociation',
        ),
    ]
