# Generated by Django 5.0.3 on 2024-04-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('weight', 'weight'), ('Age', 'Age')], max_length=100),
        ),
    ]
