# Generated by Django 5.0.3 on 2024-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_puppy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
