# Generated by Django 5.0.2 on 2024-03-09 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def get_default_user():
    User = settings.AUTH_USER_MODEL
    return User.objects.first()

class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitem_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(default=get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
