# Generated by Django 5.0.3 on 2024-06-01 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='order',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='orderproduct',
        #     name='order',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        # ),
        # migrations.AddField(
        #     model_name='orderproduct',
        #     name='product',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        # ),
        # migrations.AddField(
        #     model_name='orderproduct',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='payment',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='orderproduct',
        #     name='payment',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.payment'),
        # ),
        # migrations.AddField(
        #     model_name='order',
        #     name='payment',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.payment'),
        # ),
        # migrations.AddField(
        #     model_name='shipping_addresses',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='order',
        #     name='shipping_address',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_of_shipping', to='order.shipping_addresses'),
        # ),
        # migrations.AddField(
        #     model_name='wallet',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='transaction',
        #     name='wallet',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='order.wallet'),
        # ),
    ]
